# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/al/Projects_My/NLP-russian-language/examples/recognition_text/creater_array_marked_char/Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_Wind(object):
    def setupUi(self, Main_Wind):
        Main_Wind.setObjectName("Main_Wind")
        Main_Wind.resize(1000, 480)
        self.buttonBox = QtWidgets.QDialogButtonBox(Main_Wind)
        self.buttonBox.setGeometry(QtCore.QRect(10, 440, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.Dialog_file_label = QtWidgets.QLabel(Main_Wind)
        self.Dialog_file_label.setGeometry(QtCore.QRect(30, 30, 121, 17))
        self.Dialog_file_label.setObjectName("Dialog_file_label")
        self.lineEdit = QtWidgets.QLineEdit(Main_Wind)
        self.lineEdit.setGeometry(QtCore.QRect(150, 30, 561, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Main_Wind)
        self.label.setGeometry(QtCore.QRect(70, 80, 67, 17))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(Main_Wind)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 80, 501, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(Main_Wind)
        self.label_2.setGeometry(QtCore.QRect(70, 120, 67, 17))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Main_Wind)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 120, 221, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(Main_Wind)
        self.pushButton.setGeometry(QtCore.QRect(670, 80, 151, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Main_Wind)
        self.pushButton_2.setGeometry(QtCore.QRect(830, 80, 161, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Main_Wind)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 120, 161, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Main_Wind)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 120, 151, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(Main_Wind)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 180, 121, 151))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Main_Wind)
        self.lineEdit_5.setGeometry(QtCore.QRect(300, 240, 61, 51))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_5 = QtWidgets.QPushButton(Main_Wind)
        self.pushButton_5.setGeometry(QtCore.QRect(380, 290, 151, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Main_Wind)
        self.pushButton_6.setGeometry(QtCore.QRect(540, 290, 191, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Main_Wind)
        self.pushButton_7.setGeometry(QtCore.QRect(380, 240, 111, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Main_Wind)
        self.pushButton_8.setGeometry(QtCore.QRect(730, 30, 171, 25))
        self.pushButton_8.setObjectName("pushButton_8")

        self.retranslateUi(Main_Wind)
        self.buttonBox.accepted.connect(Main_Wind.accept)
        self.buttonBox.rejected.connect(Main_Wind.reject)
        QtCore.QMetaObject.connectSlotsByName(Main_Wind)

    def retranslateUi(self, Main_Wind):
        _translate = QtCore.QCoreApplication.translate
        Main_Wind.setWindowTitle(_translate("Main_Wind", "Dialog"))
        self.Dialog_file_label.setText(_translate("Main_Wind", "Выберите файл"))
        self.label.setText(_translate("Main_Wind", "Строка"))
        self.label_2.setText(_translate("Main_Wind", "Слово"))
        self.pushButton.setText(_translate("Main_Wind", "Следующая строка"))
        self.pushButton_2.setText(_translate("Main_Wind", "Предыдущая строка"))
        self.pushButton_3.setText(_translate("Main_Wind", "Следующее слово"))
        self.pushButton_4.setText(_translate("Main_Wind", "Предыдущее слово"))
        self.pushButton_5.setText(_translate("Main_Wind", "Следующий символ"))
        self.pushButton_6.setText(_translate("Main_Wind", "Предыдущий символ"))
        self.pushButton_7.setText(_translate("Main_Wind", "Записать"))
        self.pushButton_8.setText(_translate("Main_Wind", "Выберите файл"))
